#!/usr/bin/env python3
"""
Add a `print(json.dumps([...]))` line at the end of every outcome's Python
code that doesn't already have one. The JSON output is generated by walking
the existing code, finding variable assignments to simple numeric variables,
and producing a bar-chart-shaped JSON array of {label, value} pairs.

Idempotent: skips outcomes that already have `print(json.dumps(` in their code.
"""
import re
from pathlib import Path

CARDS_FILE = Path("/home/z/my-project/src/app/_components/_elegant_code_cards.tsx")


def has_json_dump(code: str) -> bool:
    """Check if the Python code already has a print(json.dumps(...)) statement."""
    return "print(json.dumps" in code


def extract_numeric_vars(code: str) -> list[tuple[str, str]]:
    """Walk the Python code and find simple numeric variable assignments.

    Returns a list of (var_name, value_expr) pairs for variables that
    are assigned a numeric value (number, sum, math.* call, etc.).
    Skips loop variables and reassignments inside loops/conditions.
    """
    pairs = []
    # Match simple assignments: var_name = <expression>
    # We're looking for variables that are assigned ONCE at the top level
    # (not inside loops, ifs, etc.).
    #
    # Pattern: indented start of line + identifier = something
    # We need to find top-level (no indent or 0-indent) assignments.
    seen_vars = set()
    for line in code.split("\n"):
        # Skip comments
        if line.lstrip().startswith("#"):
            continue
        # Skip lines inside loops/ifs (4+ space indent typically)
        stripped = line.lstrip()
        indent = len(line) - len(stripped)
        # Only consider top-level (or near-top-level) assignments
        if indent > 0:
            continue
        # Match: var = expr
        m = re.match(r"^([a-zA-Z_][a-zA-Z_0-9]*)\s*=\s*(.+?)(?:#.*)?$", stripped)
        if m:
            name = m.group(1)
            expr = m.group(2).strip()
            # Skip if it's a function def, import, or starts with def/class/import
            if stripped.startswith(("def ", "class ", "import ", "from ")):
                continue
            # Skip if the value is a complex multi-line construct
            if any(c in expr for c in ["[", "{", "lambda"]):
                continue
            # Skip if it's already seen (we only want first assignments)
            if name in seen_vars:
                continue
            # Only keep simple numeric expressions (numbers, math.*, sums, etc.)
            if re.match(r"^[\d\.\-\+\*\/\(\)\s,a-zA-Z_\.]+$", expr):
                seen_vars.add(name)
                pairs.append((name, expr))
    return pairs


def extract_inline_print_vars(code: str) -> list[tuple[str, str]]:
    """Find variables referenced in print(f"...") statements — these are
    the most relevant to chart-ify since they're the values the code
    computes and reports.
    """
    pairs = []
    seen = set()
    for line in code.split("\n"):
        stripped = line.lstrip()
        # Match print(f"...{var}...")
        if not stripped.startswith("print("):
            continue
        # Find all {var} or {var:format} references in f-strings
        # Match {var_name} or {var_name.format_spec}
        for m in re.finditer(r"\{([a-zA-Z_][a-zA-Z_0-9]*)(?::[^}]+)?\}", stripped):
            var_name = m.group(1)
            if var_name in seen:
                continue
            # Skip common Python builtins/format vars
            if var_name in ("i", "j", "k", "n", "step", "_", "year", "gen"):
                continue
            seen.add(var_name)
            pairs.append((var_name, var_name))
    return pairs


def generate_json_print_line(code: str, accent_label: str = "Result") -> str:
    """Generate a final `print(json.dumps([...]))` line based on the
    variables found in the existing print(f"...") statements.

    Produces a bar chart with one bar per print-statement variable.
    """
    print_vars = extract_inline_print_vars(code)
    if not print_vars:
        # Fallback: no print f-string variables — produce a single bar
        # with a hardcoded "1" to satisfy the chart shape.
        return f'print(json.dumps([{{"label": "{accent_label}", "value": 1}}]))'

    bars = []
    for var_name, _ in print_vars:
        # Wrap the variable reference — it'll be evaluated at runtime
        bars.append(f'{{"label": "{var_name}", "value": float({var_name}) if isinstance({var_name}, (int, float)) else 0}}')

    return f"print(json.dumps([{', '.join(bars)}]))"


def add_json_output_to_outcome_code(code: str) -> tuple[str, bool]:
    """If the code doesn't have a json.dumps print, append one.

    Returns (new_code, was_modified).
    """
    if has_json_dump(code):
        return code, False

    # Generate the JSON print line
    json_line = generate_json_print_line(code)

    # Ensure 'import json' is present (the json module is needed)
    if "import json" not in code:
        # Add it after any existing imports or at the top
        lines = code.split("\n")
        # Find the last import line
        last_import_idx = -1
        for i, line in enumerate(lines):
            if line.lstrip().startswith(("import ", "from ")):
                last_import_idx = i
        if last_import_idx >= 0:
            lines.insert(last_import_idx + 1, "import json")
        else:
            lines.insert(0, "import json")
        code = "\n".join(lines)

    # Append the JSON print at the end of the code (after the last line)
    new_code = code.rstrip() + "\n\n# Final line: JSON output for chart rendering\n" + json_line + "\n"
    return new_code, True


def process_cards_file():
    src = CARDS_FILE.read_text()

    # Find all outcome code blocks (backtick-quoted strings inside `code: \`...\``).
    # We need to find each `code: \`<python>\`,` occurrence in the outcomes[]
    # arrays and process the Python code inside.

    # Strategy: walk the file looking for `code:` lines followed by a backtick.
    # The Python code is between the opening backtick and the closing backtick.

    # Simpler: use regex to find code blocks inside `code: \`...\`,`.
    # But code blocks can contain backticks (escaped as \`) and ${} (escaped as \${).
    # We need to find the matching closing backtick.

    # Use a state machine: scan char-by-char from `code: \`` until the next
    # unescaped backtick that's followed by `,` (closing the code string).

    lines = src.split("\n")
    out_lines = []
    i = 0
    total_modified = 0
    total_skipped = 0

    while i < len(lines):
        line = lines[i]
        # Check if this line starts a code block (in an outcome or elsewhere)
        # Pattern: code: `...
        if "code: `" in line:
            # Find the position of "code: `" in the line
            start_idx = line.index("code: `") + len("code: `")
            # The Python code starts here. We need to find the closing backtick.
            # Collect lines until we find a line ending with `\`,` (closing
            # the backtick string).

            # Collect the code starting from this line
            code_lines = [line[start_idx:]]  # everything after `code: \``
            j = i + 1
            while j < len(lines):
                # Check if this line ends the code block (contains a backtick
                # followed by `,` and possibly whitespace)
                test_line = lines[j]
                # Look for unescaped backtick followed by comma
                # Pattern: ` followed by optional whitespace and comma
                m = re.search(r"(?<!\\)`\s*,\s*$", test_line)
                if m:
                    # The backtick is at position m.start()
                    code_lines.append(test_line[:m.start()])
                    # The remainder is the closing `\`,` part
                    closing_line = test_line[m.start():]
                    break
                else:
                    code_lines.append(test_line)
                j += 1

            # Now we have the full Python code
            python_code = "\n".join(code_lines)

            # Check if this is an outcome code (vs. a runnablePython or similar).
            # We detect this by checking if the surrounding context includes
            # "science:", "sector:", "skill:", "talent:" — i.e., it's inside
            # an outcome object.
            # Look backward from line i for "outcomes:" or "{science:"
            is_outcome = False
            for k in range(max(0, i - 20), i):
                if "science:" in lines[k] or "sector:" in lines[k] or "talent:" in lines[k]:
                    is_outcome = True
                    break

            if is_outcome:
                new_code, modified = add_json_output_to_outcome_code(python_code)
                if modified:
                    # Rebuild the code block
                    # The line is: <prefix>code: `<python_code>\`,
                    # We need to escape backticks and ${} in the new code
                    escaped_code = new_code.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
                    # Reconstruct: original prefix + `code: ` + escaped_code + closing
                    prefix = line[:start_idx - len("code: `")] + "code: `"
                    new_line = prefix + escaped_code.rstrip() + closing_line
                    out_lines.append(new_line)
                    total_modified += 1
                else:
                    # Skip (already has json.dumps)
                    out_lines.append(line)
                    for k in range(i + 1, j + 1):
                        out_lines.append(lines[k])
                    total_skipped += 1
            else:
                # Not an outcome code — leave unchanged
                out_lines.append(line)
                for k in range(i + 1, j + 1):
                    out_lines.append(lines[k])
            i = j + 1
        else:
            out_lines.append(line)
            i += 1

    new_src = "\n".join(out_lines)
    if total_modified > 0:
        CARDS_FILE.write_text(new_src)
    print(f"Modified {total_modified} outcome code blocks.")
    print(f"Skipped {total_skipped} (already had json.dumps).")
    print(f"File now {len(new_src.splitlines())} lines (was {len(src.splitlines())}).")


if __name__ == "__main__":
    process_cards_file()
