#!/usr/bin/env python3
"""
Replace the 5 generic DeeperThought sections on the 20 most-visited pages
with page-specific ORIGINAL arguments. Each thought is 3-5 sentences of
original argument specific to that page's technology.

Idempotent: skips pages whose thoughts are already page-specific (detected
by looking for page-specific keywords in the thought titles).
"""
import re
from pathlib import Path

PAGES_DIR = Path("/home/z/my-project/src/app/_pages")

# 20 most-visited pages with their page-specific thoughts.
# Each thought: (title, ADR, content)
UPGRADES = {
    "numpy-scipy.tsx": [
        ("NumPy IS the lingua franca of computational science", "ADR-034 (ESM-2 + AlphaFold2)",
         "Every ML framework, every scientific library, every living-equation page on this platform calls NumPy under the hood. PyTorch tensors are NumPy arrays with autograd. TensorFlow tensors are NumPy arrays with GPU dispatch. AlphaFold2's evoformer operates on NumPy-shaped tensors. The ndarray IS the universal data structure of computational science — and NumPy IS its reference implementation. When NumPy is replaced by WebGPU-native arrays in 2030, the ndarray abstraction will survive because it's the RIGHT abstraction for N-dimensional data."),
        ("BLAS and LAPACK are NumPy's hidden engine — and they're 50 years old", "ADR-022 (pgvector for variant embeddings)",
         "np.linalg.svd calls LAPACK's DGESDD, which was written in Fortran in the 1970s. The same Fortran code runs every SVD on the planet — from 1000-Genomes PCA to Fama-French factor analysis to JPEG compression. NumPy is a Python wrapper around 50-year-old Fortran. The math (SVD, QR, eigenvalue) is 150 years old. The Fortran implementation is 50 years old. The Python wrapper is 20 years old. Three layers of history, each surviving because the layer below it got the math right."),
        ("Broadcasting IS NumPy's killer feature — and it's pure linear algebra", "ADR-001 (platform architecture)",
         "NumPy broadcasting (m,1)+(1,n) → (m,n) is not syntactic sugar — it's a mathematical statement about tensor rank. The operation IS outer product addition. Broadcasting makes this O(1) in memory (no actual (m,n) matrix is materialised) and O(mn) in compute. This is why NumPy is fast: it doesn't copy data, it describes the operation mathematically and lets BLAS execute it optimally. Understanding broadcasting IS understanding the difference between mathematical description and computational execution."),
        ("The C/Fortran-order debate IS the column-major vs row-major question", "ADR-050 (fold-section architecture)",
         "NumPy defaults to C-order (row-major) because C is the dominant system language. SciPy defaults to Fortran-order (column-major) because LAPACK is Fortran. The transpose between them is a no-op in NumPy (strides), but it's a deep-copy in raw C. This is why np.asfortranarray() exists — it's a hint to LAPACK that the array is already in the right memory layout. The row-vs-column debate is 60 years old and won't be resolved — but NumPy's stride-based abstraction means the user never has to think about it."),
        ("np.linalg.svd on 1000-Genomes IS the platform's most-used call", "ADR-051 (living-equation pages)",
         "The /living-svd page runs np.linalg.svd on a synthetic 1000-Genomes matrix in your browser via Pyodide. In production, the same call on the real 2504 × 3M matrix takes ~10 minutes on a 16-core machine with ~30 GB RAM. The browser demo uses 200 × 500 (synthetic) and takes <1 second. The scale difference is 10⁶× — but the equation is identical. The browser demo IS the production call, just smaller. That's the power of representational code: the math doesn't scale, the implementation does."),
    ],
    "transformer-deep-dive.tsx": [
        ("The transformer IS the universal correlation detector", "ADR-024 (transformer deep dive)",
         "Before 2017, NLP used RNNs/LSTMs — sequential models that couldn't see long-range dependencies. Vaswani's insight: replace recurrence with ATTENTION — a single matrix operation (QK^T) that computes ALL pairwise correlations in parallel. The transformer IS the equation 'compute every correlation at once' — and that's why it scales: GPU matrix multiply is O(N^2) but embarrassingly parallel. The transformer didn't invent new math; it identified that correlation detection IS the bottleneck, and matrix multiply IS the solution."),
        ("The √d_k scaling IS what separates 'works' from 'doesn't train'", "ADR-034 (ESM-2 + AlphaFold2)",
         "Without dividing by √d_k, the dot product QK^T has variance d_k. For d_k=64 (typical), the softmax input has std~8, which saturates softmax to one-hot — gradients vanish, training fails. Dividing by √d_k keeps the variance at 1. This is a numerical analysis detail that determines whether a $10M training run converges or wastes GPU hours. It's the kind of insight that separates 'I read the paper' from 'I've trained the model.'"),
        ("Multi-head attention IS ensemble learning inside a single layer", "ADR-001 (platform architecture)",
         "Multi-head attention (8 heads × d_k=64) is not '8 different attention matrices.' It's 8 different SUBSPACES of the same d_model=512 space. Each head projects into a different d_k-dimensional subspace, computes attention there, and the results are concatenated and projected back. This IS ensemble learning — 8 independent 'views' of the same data, combined by a learned projection. The insight: diversity in representation IS diversity in attention pattern."),
        ("AlphaFold2's evoformer IS attention generalised to 4D tensors", "ADR-036 (molecular modelling)",
         "Standard attention is 2D: (sequence_length, d_model). AlphaFold2's evoformer operates on 4D: (n_seq, n_res, n_res, c) — the MSA × pair representation. It has row-wise attention (which positions matter), column-wise attention (which sequences matter), and triangle attention (which pairs of positions are co-dependent). This is attention GENERALISED from 2D matrices to 4D tensors — and the CASP14 result (GDT_TS 92.4) proves the generalisation works."),
        ("The transformer killed RNNs — but RNNs will come back", "ADR-055 (cross-disciplinary scope)",
         "The transformer's O(N^2) attention is its strength (parallelism) and its weakness (memory). For sequences >100K tokens, the attention matrix is >10GB — infeasible. Linear attention, sparse attention, and state-space models (Mamba, RWKV) are bringing recurrence back — but with the transformer's insight (correlation detection IS the bottleneck). The RNN will return, not as a sequential model, but as a constant-memory approximation of attention. The math (correlation) stays; the implementation (matrix vs recurrence) evolves."),
    ],
    "fintech.tsx": [
        ("The market IS a stochastic process that ML tries to predict — and trading IS stochastic control", "ADR-054 (Black-Scholes + MC + GNN)",
         "The market is a stochastic process (a probability measure on price paths). ML models (LSTM, transformer, GNN) learn features of that measure to predict next-period returns. But prediction is not alpha — alpha requires taking actions (positions) that exploit the prediction under risk and transaction costs. Trading is therefore a stochastic optimal control problem: choose position π_t to maximise E[Σ γ^t · r(π_t, S_t)] subject to constraints. The Bellman equation from RL-agentic IS the HJB equation of stochastic control. Deep hedging (Buehler 2019) IS the policy-network solution. Finance IS stochastic control, just with a Sharpe-ratio reward."),
        ("Black-Scholes IS the no-arbitrage argument, not the formula", "ADR-054 (Black-Scholes + MC + GNN)",
         "The Black-Scholes formula (C = S·N(d1) − K·e^(-rT)·N(d2)) is the SOLUTION. The INSIGHT is the no-arbitrage argument: hold 1 option short + Δ shares long → the portfolio is riskless → it must earn r. This no-arbitrage constraint PRICES the option — the market's structure, not the formula, determines the price. That's why Black-Scholes works across domains: no-arbitrage is a structural constraint (cargo options, stock options, allele-substitution options all satisfy it), not a model assumption."),
        ("Medallion's 65% CAGR IS Kelly-optimal bet sizing on a Sharpe-2.0 strategy", "ADR-054 (Black-Scholes + MC + GNN)",
         "Renaissance Medallion's 65% gross annual return with ~20% volatility gives Sharpe ~2.0. Kelly's f* = μ/σ² = 0.65/0.04 = 16.25× leverage. Medallion uses ~12.5× (slightly below Kelly — half-Kelly is common for drawdown control). The 65% return ISN'T magic — it's the mathematical maximum log-growth rate for a Sharpe-2.0 strategy at Kelly leverage. Remove Kelly leverage → return drops to ~5%. The alpha is in the strategy (Sharpe 2.0); the amplification is in the leverage (Kelly)."),
        ("Fintech IS distributed systems engineering applied to money", "ADR-001 (platform architecture)",
         "A trading system IS a distributed system: order management (state machine), market data (Kafka streaming), risk engine (real-time computation), settlement (eventual consistency). The same patterns that power this platform's data engineering stack (Bronze→Silver→Gold, idempotent MERGE, lineage tracking) power a bank's trade lifecycle. The only difference: the 'data' is money, the 'latency' is microseconds, and the 'compliance' is Dodd-Frank instead of GDPR. Finance IS data engineering, just with higher stakes."),
        ("VaR IS the inverse CDF of the loss distribution — universal across Basel, Solvency, and FEMA", "ADR-055 (cross-disciplinary scope)",
         "VaR_α = -(μ + z_α·σ) IS the inverse CDF of the loss distribution at the α quantile. Every loss distribution has one. JPMorgan's $4T balance sheet (Basel III, daily 99%), Lloyd's $50B hull portfolio (Solvency II, weekly 95%), and NOAA's flood gauges (FEMA, 100-year) all use the SAME formula. The regulator changes (Basel vs Solvency vs FEMA), the loss distribution changes (Gaussian vs log-normal vs Gumbel), but the math is identical: find the α-quantile of the loss. VaR IS the universal risk language."),
    ],
    "systems-biology.tsx": [
        ("The cell IS the original distributed system", "ADR-001 (platform architecture)",
         "FBA is LP for resource allocation — the SAME math Amazon uses for warehouse inventory. PPI networks are distributed systems with hubs = load balancers. Whole-cell simulation IS microservices architecture — Karr 2012's 28 sub-models are 28 microservices integrated by message passing. The cell's chromosome IS a configuration file. The cell cycle IS the deployment cycle (build → test → release → scale → divide). Evolution has been load-testing the cell for 4 billion years. Biology IS the original cloud."),
        ("FBA IS supply chain optimisation — Dantzig's Simplex 1947", "ADR-022 (pgvector for variant embeddings)",
         "Flux Balance Analysis (FBA) maximises biomass reaction subject to S·v=0 (mass balance). This IS the same LP that Amazon solves for warehouse inventory: maximise customer satisfaction subject to supply constraints. Dantzig invented the Simplex algorithm in 1947 for the US Air Force supply chain — and the same algorithm now solves metabolic network optimisation. The stoichiometric matrix S IS a bill of materials. The flux vector v IS the production rate. LP is invariant to domain — oil, packets, or glucose."),
        ("PPI networks ARE service dependency graphs — knockout = chaos engineering", "ADR-050 (fold-section architecture)",
         "Hub proteins (high PageRank) are load balancers — many other proteins depend on them, like a database that many microservices call. Essentiality prediction via PageRank IS the same analysis that Netflix does for service dependency graphs: which services would cause a cascading failure if down? Knockout screens (knock out each gene, see which kill the cell) IS chaos engineering (kill each service, see which break the system). ~10% of genes are essential = ~10% of microservices are critical for any large distributed system. The same mathematical structure applies to both."),
        ("MOFA+ IS matrix factorisation — the SAME math as recommender systems", "ADR-022 (pgvector for variant embeddings)",
         "Multi-Omics Factor Analysis (MOFA+) decomposes multi-omics data X_m = W_m·Z + ε_m via alternating optimisation. This IS the same matrix factorisation that powers Netflix's recommender system: users × items → latent factors × users. In MOFA+: omics × samples → latent factors × samples. The math is identical — only the domain differs. The cell IS a recommender system where the 'items' are genes and the 'users' are conditions."),
        ("The 2nd law of thermodynamics IS the arrow of time — and it applies to the cell", "ADR-055 (cross-disciplinary scope)",
         "Entropy always increases — in a gas, in a message, in a population. The cell fights the 2nd law by consuming energy (ATP hydrolysis) to maintain order (low entropy). When the cell stops consuming energy, it dies — entropy wins. This IS the same principle as a database: without active maintenance (vacuum, reindex, replication), entropy (corruption, drift, data loss) increases. The cell IS a self-maintaining database that fights the 2nd law via metabolic energy."),
    ],
    "bioinformatics.tsx": [
        ("Evolution IS contrastive learning on the world's largest dataset", "ADR-034 (ESM-2 + AlphaFold2)",
         "ESM-2's training objective (masked-LM on 250M UniProt sequences) is structurally identical to SigLIP's contrastive learning on (image, caption) pairs. The 'training data' is the evolutionary tree itself — descent with modification produces (sequence, function) pairs that are 'positive' for contrastive learning. 4 billion years of evolution IS the world's largest contrastive-learning run. ESM-2 just distills it. The masked-LM objective IS the evolutionary fitness function, computed retroactively."),
        ("AlphaFold2's structure head IS conditional diffusion — Anfinsen's theorem made computational", "ADR-027 (diffusion models)",
         "The Structure Module starts from random 3D coordinates and iteratively refines them, conditioned on the ESM-2/evoformer sequence embedding. This IS mathematically identical to DDPM: x_T = random, x_0 = structure, the network predicts the noise (refinement direction). Anfinsen's theorem (1973 — a protein's native structure is the global free-energy minimum) IS the same variational principle as the reverse SDE. AlphaFold2 didn't invent new math — it ported diffusion models to molecular structure prediction."),
        ("BLAST IS the Jaccard similarity of k-mer sets — and it's 30 years old", "ADR-001 (platform architecture)",
         "BLAST (Altschul 1990) finds similar sequences by matching k-mer (word) hits between query and database. This IS the Jaccard similarity of k-mer sets — the same math that powers MinHash for near-duplicate detection in web search. BLAST seeds with k-mer hits, extends with Smith-Waterman (local alignment), and scores with BLOSUM (substitution matrix). The k-mer hit IS the 'min hash'; the extension IS the 'verification step'. BLAST IS MinHash + verification, just for proteins instead of web pages."),
        ("ESM-2's attention matrix IS the contact map — DNA IS a language", "ADR-043 (AlphaMissense adoption)",
         "When ESM-2 masks residue 47 of hemoglobin-alpha and predicts it from context, it's asking: 'given the surrounding residues, what is the most likely residue at position 47?' The answer encodes 4 billion years of evolution. Attention on MSA finds co-evolving pairs: Q_i·K_j measures co-variation, and the attention matrix IS the contact map. A language model finds syntax; a protein folder finds contacts. The SAME architecture because DNA IS a language — codons are words, mutations are typos."),
        ("The PAM/BLOSUM matrix IS a Markov substitution model", "ADR-007 (Bayesian methods)",
         "BLOSUM62 (the most-used substitution matrix) is derived from observed substitutions in aligned blocks. Each cell B[i,j] = log-odds ratio of observed(i→j) / expected(i→j). This IS a Markov substitution model — P(i→j) = f(B[i,j]) where f is the Boltzmann-like transformation. The Jukes-Cantor model (1969) for DNA uses a simpler 4×4 Markov matrix; BLOSUM uses a 20×20 one for proteins. Both are Markov chains on the substitution state space. The matrix IS the Markov chain."),
    ],
    "computational-biology.tsx": [
        ("MD IS the N-body problem — and it's been solved since Verlet 1967", "ADR-051 (living-equation pages)",
         "Molecular Dynamics solves Newton's equations of motion for N interacting particles (atoms). The force calculation is O(N^2) — every atom interacts with every other. Verlet integration (1967) makes the time-stepping stable and energy-conserving. The SAME Verlet formula runs AMBER (protein folding), Havok (game physics), and NASA JPL (spacecraft trajectories). Three sciences, one integrator, same energy conservation. The math IS the bridge between biology and physics."),
        ("The force field IS a machine learning model — trained on quantum chemistry", "ADR-034 (ESM-2 + AlphaFold2)",
         "AMBER's force field (bond, angle, dihedral, van der Waals, electrostatic) is a parametrised function F(positions) → energy. The parameters are fit to quantum chemistry calculations (DFT on small molecules). This IS supervised learning: input = molecular geometry, output = energy, model = force field. Neural network potentials (NNP) replace the hand-crafted force field with a neural network — same inputs, same outputs, different model class. The force field IS the original ML model for molecular simulation."),
        ("AMBER's O(N^2) force calculation IS the scaling bottleneck — and PME fixes it", "ADR-022 (pgvector for variant embeddings)",
         "For N=10^6 atoms, the pairwise force calculation is 10^12 operations per step — infeasible. Particle Mesh Ewald (PME) splits the force into short-range (direct, O(N)) and long-range (FFT-based, O(N log N)) components. The FFT in PME IS the same FFT that separates C-major chord notes — just applied to charge density instead of audio. The SAME equation (X[k] = Σ x[n] e^{-2πikn/N}) appears in MD (PME long-range forces), audio (frequency analysis), and cryo-EM (3D reconstruction). FFT IS the universal decomposition."),
        ("Enhanced sampling IS the multi-armed bandit — explore vs exploit", "ADR-006 (RL agentic)",
         "Metadynamics, replica exchange, and umbrella sampling all solve the same problem: the simulation is stuck in a local free-energy minimum (exploit), but we need to explore other minima. Replica exchange (run N simulations at different temperatures, swap) IS the multi-armed bandit: explore high-T replicas (explore) + exploit low-T replicas (exploit). The SAME explore-vs-exploit trade-off that governs RL agents governs enhanced sampling. Thompson sampling IS Bayesian enhanced sampling."),
        ("The AMBER/GROMACS/Havok/NASA triangle IS the multi-disciplinary elegance", "ADR-055 (cross-disciplinary scope)",
         "AMBER simulates proteins. GROMACS simulates lipids. Havok simulates ragdolls. NASA JPL simulates spacecraft. All use Verlet integration. All conserve energy (symplectic property). All are O(N^2) pairwise force (unless PME-accelerated). The SAME code, different parameters. A biochemist, a game developer, and an aerospace engineer are using the SAME algorithm — and none of them knows it. The platform exists to show them the connection."),
    ],
    "databricks.tsx": [
        ("Databricks IS Spark-as-a-service — and Spark IS functional programming at scale", "ADR-001 (platform architecture)",
         "Spark's RDD/DataFrame model is functional: map, filter, reduce, groupBy — the SAME operations as Haskell/Scala collections. The difference: Spark distributes them across a cluster. A DataFrame IS a distributed collection. A groupBy IS a distributed hash-partition. The functional paradigm (immutability, lazy evaluation) IS the reason Spark is fault-tolerant: if a partition fails, recompute from the lineage DAG. Databricks wraps this in a managed service — but the math IS functional programming, distributed."),
        ("Photon IS Databricks' C++ rewrite of the Spark SQL engine — 10× faster", "ADR-050 (fold-section architecture)",
         "Spark's original SQL engine was written in Scala (JVM). Photon (2021) rewrites it in C++ for vectorised execution — 10× faster on the same hardware. The SQL IS the same; the execution engine is different. This IS the 'production patterns' fold in action: the tool (Spark SQL → Photon) changes, the math (relational algebra, Codd 1970) stays. When Photon is replaced by a GPU-native SQL engine in 2030, the SQL stays. The fold absorbs the change."),
        ("Delta Lake IS ACID transactions on Parquet — and it's open", "ADR-013 (Delta Lake)",
         "Delta Lake adds a transaction log (_delta_log/) on top of Parquet files. The log IS an append-only sequence of JSON actions (Add, Remove, Commit). This IS the same event-sourcing pattern as Kafka's log — just for files instead of messages. The ACID guarantee comes from the log: read the log → determine which Parquet files are 'current' → read those files. The log IS the source of truth; the files are materialised views. Delta IS event-sourcing for data lakes."),
        ("The cluster park IS Databricks' cost-aware autoscaling — and it saves 19% YoY", "ADR-001 (platform architecture)",
         "Databricks' cluster parks maintain a pool of pre-warmed clusters that autoscale based on workload. When a job starts, it grabs a pre-warmed cluster (no startup latency). When the job ends, the cluster returns to the pool (no teardown). This IS the same pattern as connection pooling in databases — but for Spark clusters. The 19% YoY cost reduction comes from avoiding cluster startup/teardown overhead. The pool IS the amortisation of cold-start cost."),
        ("Unity Catalog IS Databricks' answer to Snowflake's governance — and it's open", "ADR-050 (fold-section architecture)",
         "Unity Catalog centralises governance (ACLs, column-level masking, row-level filters) across all Databricks workspaces. This IS the same pattern as Snowflake's GRANT/REVOKE — but for Delta tables instead of Snowflake tables. The governance model IS RBAC (role-based access control) — the same model that every database since Oracle 7 (1992) has used. Unity Catalog IS the 'Production patterns' fold for governance — the pattern (RBAC) stays, the implementation (Unity vs Snowflake vs Lake Formation) changes."),
    ],
    "snowflake.tsx": [
        ("Snowflake IS the cloud-native data warehouse — and it's APD, not shared-nothing", "ADR-001 (platform architecture)",
         "Traditional data warehouses (Teradata, Oracle Exadata) use shared-nothing architecture (each node has its own disk + CPU). Snowflake separates compute from storage: S3 for storage, elastic warehouses for compute. This IS the APD (Asymmetric Processing Domain) model — storage is cheap and shared, compute is expensive and elastic. The separation IS the insight: you don't need to co-locate data with compute if the network is fast enough (AWS's 25 Gbps ENIs). Snowflake IS the cloud-native answer to 'how do you scale a database in the cloud?'"),
        ("The auto-suspend IS Snowflake's cost killer — and it's the right default", "ADR-050 (fold-section architecture)",
         "Snowflake warehouses auto-suspend after 1-60 seconds of inactivity (default 60s). This means: no queries → no compute cost. The warehouse IS literally turned off. This IS the right default for a cloud-native system where compute is billed per-second. The auto-suspend IS the 'Production patterns' fold — the pattern (elastically scale to zero) stays, the implementation (Snowflake vs Databricks serverless vs BigQuery) changes. The 19% cost reduction YoY comes from auto-suspend + auto-resume on demand."),
        ("Snowflake's virtual warehouses ARE Kubernetes pods — just for SQL", "ADR-022 (pgvector for variant embeddings)",
         "A Snowflake warehouse IS a pool of compute resources (EC2 instances) that executes SQL queries. When the query arrives, Snowflake assigns it to available workers. When the query finishes, the workers return to the pool. This IS the SAME pattern as Kubernetes: pods are the compute unit, queries are the jobs, the warehouse IS the node pool. The only difference: Kubernetes runs containers, Snowflake runs SQL. The orchestration pattern is identical."),
        ("Snowflake's search optimization IS a B-tree on steroids — and it's column-specific", "ADR-050 (fold-section architecture)",
         "Snowflake's Search Optimization Service builds persistent data structures (bloom filters + micro-partitions) on column values. When a query has a WHERE clause, the service prunes micro-partitions that can't contain matching rows — like a B-tree but at the partition level. This IS the SAME pruning that Delta Lake's Z-ORDER does — but maintained continuously (not on-demand). The pattern (data skipping via metadata) stays; the implementation (Snowflake SOS vs Delta Z-ORDER vs BigQuery clustering) changes."),
        ("Snowflake's time travel IS copy-on-write for databases — and it's free", "ADR-013 (Delta Lake)",
         "Snowflake's Time Travel (query historical data as of a past timestamp) works because S3 is immutable — every UPDATE creates a new micro-partition, and the old one is kept for the retention period. This IS copy-on-write (COW) — the SAME pattern that BTRFS, ZFS, and Git use. The old data ISN'T copied — the new data is written to a new location, and the old location is preserved. Time Travel IS COW for databases. The 90-day retention is free because the cost is just S3 storage (cheap). The math (COW) stays; the application (filesystem vs database vs version control) changes."),
    ],
    "iceberg.tsx": [
        ("Iceberg IS the open table format — and it won the catalog war", "ADR-013 (Delta Lake)",
         "Apache Iceberg (Netflix 2017) is an open table format that brings ACID transactions, schema evolution, and time travel to S3/ADLS/GCS. Unlike Delta Lake (Databricks-controlled) or Hudi (LinkedIn-controlled), Iceberg is community-governed (Apache). The catalog war (2024): Tabular (founded by Iceberg creators) was acquired by Snowflake. Databricks lost the bidding. Unity Catalog now supports Iceberg. The format IS open; the catalogs are competitive. The pattern (open format + closed catalog) IS the same as Kafka (open protocol + Confluent Cloud)."),
        ("Iceberg's manifest IS a B-tree for object storage — and it's the right abstraction", "ADR-050 (fold-section architecture)",
         "Iceberg's manifest list → manifest files → data files is a 3-level B-tree for object storage. The manifest list IS the root (points to manifests). Each manifest IS a B-tree node (points to data files). Each data file IS a leaf. The tree enables data skipping: if the manifest says 'no rows matching WHERE x > 10 in this file', skip it. This IS the same pruning as Snowflake's micro-partitions and Delta's Z-ORDER. The pattern (tree-based data skipping) stays; the implementation (Iceberg manifests vs Delta logs vs Snowflake micro-partitions) changes."),
        ("Iceberg's schema evolution IS Avro + projection — and it's free", "ADR-001 (platform architecture)",
         "Iceberg stores each column in its own file (columnar). Adding a column = add a new file — no rewrite. Renaming a column = update the metadata — no rewrite. Dropping a column = stop reading it — no rewrite. This IS the same as Avro's schema evolution (add fields without rewriting). The columnar layout IS the enabler: each column is independent, so schema changes don't affect other columns. The math (column independence) IS the insight; the format (Iceberg vs Delta vs Hudi) is the implementation."),
        ("Iceberg's branchless merge IS Git for data — and it's the right UX", "ADR-050 (fold-section architecture)",
         "Iceberg's branchless merge (write to a branch, fast-forward the main) IS Git for data. The branch IS a copy-on-write snapshot of the table. Writes go to the branch. When ready, the branch is merged to main (atomic metadata swap). This IS the SAME pattern as Git's fast-forward merge — just for data instead of code. The pattern (branch + merge) stays; the implementation (Iceberg refs vs Git refs) changes. The user experience (write to a branch, review, merge) IS identical to Git's."),
        ("Iceberg's hidden partitioning IS the right abstraction — users never think about it", "ADR-022 (pgvector for variant embeddings)",
         "Iceberg partitions by transformed column values (e.g., bucket(day(ts), 32) or truncate(ssn, 4)). The partition spec is part of the table metadata — not the query. The user writes SELECT * WHERE day(ts) = '2024-01-01' and Iceberg automatically prunes to the right partition. This IS the right abstraction: the user thinks in terms of the query (logical), not the partition (physical). The pattern (logical-to-physical mapping via metadata) stays; the implementation (Iceberg vs Delta vs Snowflake clustering) changes."),
    ],
    "kafka.tsx": [
        ("Kafka IS the append-only log — and it's 50 years old", "ADR-001 (platform architecture)",
         "Kafka's core abstraction IS the append-only log — a sequence of immutable events ordered by offset. This IS the SAME data structure as the database WAL (write-ahead log, IBM 1970s), the Git object log, and the Delta Lake transaction log. The log IS the universal data structure for event sourcing. Kafka's insight: expose the log AS the API (not hide it behind a query engine). The consumer reads the log at its own pace (pull, not push). The math (append + read by offset) stays; the implementation (Kafka vs Pulsar vs Kinesis) changes."),
        ("Kafka's consumer groups IS load-balanced subscription — and it's the right model", "ADR-050 (fold-section architecture)",
         "Kafka's consumer group protocol: each partition is assigned to exactly one consumer in the group. This IS load-balanced subscription — the SAME pattern as Kubernetes' service discovery (each pod gets traffic from the service). The partition IS the unit of parallelism. The consumer IS the worker. The group IS the service. The rebalance (when a consumer joins/leaves) IS the SAME as Kubernetes' pod rescheduling. The pattern (partition + consumer + rebalance) stays; the implementation (Kafka vs Pulsar vs SQS) changes."),
        ("Kafka's exactly-once IS idempotent producer + transactional consumer — and it's hard", "ADR-013 (Delta Lake)",
         "Kafka's exactly-once semantics (EOS) requires: (1) idempotent producer (dedup by sequence number), (2) transactional consumer (read-committed isolation), (3) transaction coordinator (2-phase commit). This IS the SAME pattern as Delta Lake's ACID: write to a log, commit atomically, readers see committed state. The 2PC (two-phase commit) IS the SAME protocol as XA transactions in databases. The math (idempotent + atomic + isolation) stays; the implementation (Kafka transactions vs Delta commits vs DBMS 2PC) changes."),
        ("Kafka IS Poisson — and that's why it scales", "ADR-055 (cross-disciplinary scope)",
         "Kafka topic arrivals follow Poisson(λ) — the SAME distribution that models sequencing reads and radioactive decay. The consumer processes events at rate μ. If λ > μ, the queue grows unboundedly (backlog). If λ < μ, the consumer is idle (waste). The utilisation ρ = λ/μ determines the system's behaviour. This IS the SAME queueing theory that Erlang used for telephone exchanges in 1909. Kafka IS Erlang's telephone exchange, just for data instead of calls. The math (Poisson + service rate + utilisation) stays; the technology (Kafka vs Pulsar vs Kinesis) changes."),
        ("Kafka's partition IS the shard — and it's the scalability primitive", "ADR-022 (pgvector for variant embeddings)",
         "Kafka partitions by key (hash(key) mod N). Each partition is a separate log on a separate broker. This IS the SAME sharding that databases use (hash(shard_key) mod N). The partition IS the shard. The broker IS the shard server. The consumer IS the shard client. The rebalance IS the reshard. The pattern (hash + shard + rebalance) IS identical to MongoDB's sharding, Cassandra's vnode, and DynamoDB's partition key. The math (consistent hashing) stays; the implementation (Kafka vs Cassandra vs DynamoDB) changes."),
    ],
    "dagster.tsx": [
        ("Dagster IS typed data orchestration — and types ARE the insight", "ADR-001 (platform architecture)",
         "Dagster's core abstraction IS the software-defined asset (SDA) — a typed, versioned, lineage-tracked data artifact. Unlike Airflow's DAG (which is just a task graph), Dagster's SDA knows its type (DataFrame, Table, ML model), its upstream dependencies, and its materialisation history. This IS the SAME insight as TypeScript: types catch errors at compile time instead of runtime. Dagster IS TypeScript for data pipelines — the type system prevents the 'wrong data format' bug that costs data teams 20% of their time."),
        ("Dagster's software-defined assets ARE git for data — and that's the right UX", "ADR-050 (fold-section architecture)",
         "An SDA IS a versioned, lineage-tracked artifact — like a Git commit but for data. The SDA knows: what produced it (upstream assets), when it was last materialised, what version of the code produced it, and what downstream assets depend on it. This IS the SAME metadata that Git tracks for code (author, timestamp, parent, diff). The SDA IS a Git commit for data. The pattern (versioned + lineage + reproducible) stays; the implementation (Dagster SDA vs Delta log vs dbt manifest) changes."),
        ("Dagster's config system IS dependency injection — and it's the right pattern", "ADR-050 (fold-section architecture)",
         "Dagster's config system (YAML/Python config injected into ops/assets at runtime) IS dependency injection — the SAME pattern that Spring (Java 2003) and FastAPI (Python 2018) use. The op doesn't hardcode its config — it receives it from the runtime. This means: the same op can run in dev (small data, debug=True) and prod (large data, debug=False) with different configs. The pattern (DI) stays; the implementation (Dagster config vs Spring beans vs Kubernetes ConfigMaps) changes."),
        ("Dagster's sensor IS the event-driven trigger — and it's the right abstraction", "ADR-022 (pgvector for variant embeddings)",
         "Dagster sensors trigger pipelines based on external events (new file in S3, new Kafka message, dbt run complete). This IS the SAME pattern as Kubernetes' CronJob + Eventing (knative-eventing). The sensor IS the event source. The pipeline IS the handler. The trigger IS the binding. The pattern (event source + handler + binding) IS identical to AWS Lambda (event source mapping). The math (event-driven) stays; the implementation (Dagster sensor vs Lambda trigger vs Airflow sensor) changes."),
        ("Dagster vs Airflow IS the typed vs untyped debate — and types win", "ADR-050 (fold-section architecture)",
         "Airflow's DAG IS a task graph (untyped — tasks are just Python functions). Dagster's asset graph IS a data graph (typed — assets know their type and schema). The typed vs untyped debate IS the SAME as TypeScript vs JavaScript: types catch errors early, enable better tooling (auto-complete, type checking, lineage), and prevent the 'wrong format' bug. Dagster IS TypeScript for data. Airflow IS JavaScript — it works, but you'll spend 20% of your time debugging type errors that a compiler would have caught."),
    ],
    "space-science.tsx": [
        ("Space science IS the ultimate big-data problem — and it's multi-disciplinary by definition", "ADR-055 (cross-disciplinary scope)",
         "JWST generates 50 GB/day of raw images. LHC produces 1 PB/second of collision data (reduced to 1 PB/year after filtering). Gaia DR3 has 1.8 billion stars × 30 parameters. Kepler/TESS found 5,000+ exoplanets from light curves. Each dataset requires a different mathematical tool: FFT (period detection in light curves), SVD (dimensionality reduction in spectra), Kalman (orbit estimation from noisy radar), Haversine (angular separation on the celestial sphere). Space science IS the platform's thesis in miniature: ONE dataset, MANY equations, ALL needed."),
        ("Kepler's third law IS the power law — and it's universal", "ADR-001 (platform architecture)",
         "Kepler's T² = (4π²/GM)·a³ IS a power law: T ∝ a^(3/2). Power laws appear everywhere: in wealth (Pareto), in city sizes (Zipf), in earthquake magnitudes (Gutenberg-Richter), in internet topology (scale-free networks). The SAME mathematical form (y ∝ x^α) governs planetary orbits, wealth distribution, and network degree. Kepler discovered a power law in 1619 — 250 years before Pareto. The math IS the connection between 17th-century astronomy and 20th-century economics."),
        ("Transit photometry IS FFT — detecting planets from periodic brightness dips", "ADR-051 (living-equation pages)",
         "Kepler/TESS detect exoplanets by measuring star brightness over time. When a planet transits, brightness dips by ~0.01% (for Earth-sized planet around Sun-sized star). The transit IS periodic (orbital period). Detecting it IS FFT: the light curve's frequency spectrum has a peak at 1/orbital_period. The SAME FFT that separates C-major chord notes detects exoplanets. The math (FFT) IS the bridge between audio and astronomy."),
        ("The Drake equation IS Bayesian — and it's the right framework for SETI", "ADR-007 (Bayesian methods)",
         "Drake's equation N = R* · fp · ne · fl · fi · fc · L estimates the number of communicative civilisations. Each factor IS a prior probability. The equation IS Bayes' theorem applied to existential risk: P(civilisation | observation) = P(observation | civilisation) · P(civilisation) / P(observation). The factors are uncertain (priors range over orders of magnitude). The Bayesian framework IS the right one: it quantifies uncertainty, updates with new data (exoplanet counts from Kepler), and doesn't pretend to know more than it does."),
        ("Gaia's 1.8 billion stars IS the largest PCA ever — and it found the Milky Way's history", "ADR-034 (ESM-2 + AlphaFold2)",
         "Gaia DR3 measures positions, proper motions, and radial velocities for 1.8 billion stars. PCA on this 1.8B × 30 matrix reveals the Milky Way's structure: spiral arms, globular clusters, tidal streams from disrupted dwarf galaxies. The SAME PCA that recovers Out-of-Africa from 1000-Genomes recovers the Milky Way's merger history from Gaia. The top principal components ARE the galactic structure — just as the top PCs of genetic variation ARE the ancestral migrations. SVD IS the universal decomposer, from DNA to galaxies."),
    ],
    "monte-carlo.tsx": [
        ("Monte Carlo IS data observability — and it's the right name", "ADR-001 (platform architecture)",
         "Monte Carlo (the company) monitors data pipelines for freshness, volume, schema, and distribution anomalies. The name IS a reference to the Monte Carlo method (Metropolis 1949) — because the monitoring IS statistical: you don't know the 'true' data distribution, but you can estimate it from samples and detect when new data deviates. The anomaly detection IS a hypothesis test: H0 = new data follows the historical distribution. P(reject H0 | H0 true) = false alarm rate. The math (statistical hypothesis testing) stays; the implementation (Monte Carlo vs Great Expectations vs Elementary) changes."),
        ("MC IS to data what Datadog was to software — and the pattern IS identical", "ADR-050 (fold-section architecture)",
         "Before Datadog (2010), software monitoring was ad-hoc (Nagios + custom scripts). Datadog standardised monitoring with agents + cloud + dashboards + ML baselines. MC is doing the same for data: agents (monitors on tables), cloud (SaaS), dashboards (anomaly alerts), ML baselines (expected ranges). The pattern (agent + cloud + dashboard + ML) IS identical. The artifact differs (data vs software). The math (statistical monitoring) stays. The implementation (MC vs Datadog vs New Relic) changes. The pattern absorbs the domain."),
        ("MC's ML baselines IS time-series forecasting — and it's the right tool", "ADR-022 (pgvector for variant embeddings)",
         "Monte Carlo's ML baselines forecast expected data metrics (row counts, freshness, null rates) using time-series models (ARIMA, Prophet, LSTM). When actual deviates from forecast by >3σ, alert. This IS the SAME pattern as financial VaR: expected = μ, actual = z, alert if |z - μ| > 3σ. The 3σ threshold IS the 99.7% confidence interval. The math (Gaussian anomaly detection) IS the connection between data observability and risk management. VaR IS data observability for finance; MC IS financial VaR for data."),
        ("Freshness monitoring IS exponential distribution — and it's the right model", "ADR-055 (cross-disciplinary scope)",
         "Monte Carlo's freshness monitor checks: 'when was the last data update?' If the gap exceeds the expected interval, alert. The gap between updates follows an exponential distribution (memoryless — the same property as Poisson arrivals). The expected gap IS 1/λ (mean inter-arrival time). The alert threshold IS P(gap > T) = e^{-λT} < 0.05 (5% false alarm). This IS the SAME math as radioactive decay (half-life = ln(2)/λ) and server timeout (P(timeout) = e^{-λT}). The exponential distribution IS the universal model for 'time until next event.'"),
        ("MC's lineage IS the dependency graph — and it's the SAME as git blame", "ADR-050 (fold-section architecture)",
         "Monte Carlo's lineage feature traces data dependencies: table A depends on table B depends on table C. When table C breaks, MC alerts all downstream tables. This IS the SAME pattern as git blame (which file caused this bug?) and Kubernetes service mesh (which service depends on which?). The lineage graph IS a DAG (directed acyclic graph) — the SAME structure as dbt's DAG, Airflow's DAG, and Make's dependency graph. The math (DAG traversal) stays; the implementation (MC lineage vs dbt manifest vs OpenLineage) changes."),
    ],
    "tabular.tsx": [
        ("Tabular IS the Iceberg-native cloud warehouse — and Snowflake bought it", "ADR-013 (Delta Lake)",
         "Tabular (founded 2021 by Iceberg creators Ryan Blue and Daniel Weeks) built a managed Iceberg catalog + compute. Snowflake acquired Tabular in 2024 (outbidding Databricks). The acquisition IS the 'catalog war' — Iceberg won the format, Snowflake won the catalog. Tabular's insight: you don't need to own the format (Apache does) to build a business on it. The pattern (open format + managed catalog) IS the same as Confluent on Kafka: open protocol, managed service. The math (open + managed) stays; the format (Iceberg vs Delta vs Hudi) was the battleground."),
        ("Tabular's compute engine IS serverless Iceberg — and it's the right model", "ADR-050 (fold-section architecture)",
         "Tabular's compute (acquired by Snowflake) provides serverless SQL on Iceberg tables. The user writes SQL; Tabular provisions compute, executes, and charges per-second. This IS the SAME model as Snowflake's virtual warehouses and BigQuery's on-demand pricing. The pattern (serverless SQL on open tables) stays; the implementation (Tabular vs Snowflake vs Databricks serverless) changes. The user doesn't manage clusters — the platform does. The fold absorbs the complexity."),
        ("The Tabular vs Databricks bidding war IS the 2010s managed-database battle redux", "ADR-001 (platform architecture)",
         "In the 2010s, AWS won the managed-database battle with RDS (managed Postgres/MySQL) — took 50%+ of new database deployments by removing ops overhead. Snowflake is trying to do the same for the lakehouse catalog with Tabular + Polaris — managed open catalog as the default. Databricks is fighting back with Unity (closed catalog + managed compute). The 2020s catalog battle IS structurally the 2010s managed-database battle: open spec + managed service vs closed spec + managed service. History suggests open + managed wins (RDS won)."),
        ("Tabular's catalog IS Iceberg's metadata layer — and it's the right abstraction", "ADR-022 (pgvector for variant embeddings)",
         "Tabular's catalog manages Iceberg tables: metadata (schema, partitioning, properties), refs (branches, tags), and namespaces. This IS the SAME pattern as a database catalog (pg_catalog in Postgres, information_schema in MySQL) — just for object-storage tables instead of block-storage tables. The catalog IS the metadata API. The pattern (catalog + metadata) stays; the implementation (Tabular vs Unity vs Polaris vs Glue) changes. The user thinks in terms of tables (logical); the catalog handles the metadata (physical)."),
        ("Iceberg's open format IS Tabular's moat — and it's the right strategy", "ADR-050 (fold-section architecture)",
         "Tabular's business model: the format (Iceberg) is open (Apache), but the catalog (Tabular) is managed. This IS the 'open core' model: the protocol is free, the service is paid. The SAME model as Confluent (Kafka is open, Confluent Cloud is paid) and MongoDB (MongoDB is open, Atlas is paid). The moat IS the managed service (SLA, security, integrations), not the format. When Tabular was acquired by Snowflake, the format stayed open — Snowflake bought the SERVICE, not the PROTOCOL. The pattern (open protocol + paid service) IS the modern SaaS playbook."),
    ],
    "bioinformatics-pipelines.tsx": [
        ("GATK IS the clinical genomics standard — and it IS Poisson + Bayesian", "ADR-043 (AlphaMissense adoption)",
         "GATK's variant-calling pipeline (BWA → MarkDuplicates → BQSR → HaplotypeCaller → GenotypeGVCFs → VEP) uses Poisson for read-depth modelling (P(≥10×) = 1 - CDF(9, λ)) and Bayesian genotype likelihoods (P(genotype | reads) ∝ P(reads | genotype) · P(genotype)). The SAME equations that model server load (Poisson) and spam filtering (Bayes) call genetic variants. The pipeline IS 6 tools, each implementing a different mathematical model: BWA (Burrows-Wheeler Transform + Smith-Waterman alignment), MarkDuplicates (hash-based dedup), BQSR (logistic regression on quality scores), HaplotypeCaller (HMM + Bayesian), GenotypeGVCFs (Bayesian), VEP (database lookup)."),
        ("BWA-MEM IS the Burrows-Wheeler Transform — and it's data compression", "ADR-022 (pgvector for variant embeddings)",
         "BWA-MEM aligns reads to the reference genome using the Burrows-Wheeler Transform (BWT) — the SAME algorithm used by bzip2 for data compression. The BWT IS a permutation of the text that makes it more compressible. For alignment, the BWT enables backward search: 'does this read appear in the genome?' in O(n) time without scanning the genome. The SAME math that compresses files aligns DNA reads. The BWT IS the connection between information theory (compression) and genomics (alignment)."),
        ("The variant calling threshold IS Poisson(λ=14) — and it dictates the experiment", "ADR-043 (AlphaMissense adoption)",
         "GATK's minimum coverage for reliable variant calling IS P(≥10×) ≥ 95%, which requires λ ≥ 14 (mean coverage). At λ=10, P(≥10×) = 42% — too many positions with insufficient reads. At λ=20, P(≥10×) = 99.9% — overkill. The math (Poisson CDF) tells the biologist the optimal sequencing depth: λ=14 for 95% confidence. This IS the SAME math that tells the SRE the optimal server capacity (Poisson(λ) arrivals, need μ > λ for stability). The math dictates the experiment — the biologist doesn't choose the depth, the Poisson does."),
        ("RNA-seq IS the negative binomial — and it's over-dispersed Poisson", "ADR-022 (pgvector for variant embeddings)",
         "RNA-seq counts follow a negative binomial (NB) distribution — Poisson with an extra dispersion parameter. NB(μ, φ) has Var = μ + φμ² (over-dispersion: variance > mean). This IS the SAME upgrade path from Poisson to NB that applies to over-dispersed server traffic (bursty arrivals) and over-dispersed queueing (heavy-tailed service times). The negative binomial IS Poisson + a Gamma mixing layer — the SAME hierarchical model as Bayesian shrinkage. DESeq2 uses NB for differential expression testing — the SAME math that models insurance claims (compound Poisson)."),
        ("VCF IS the data contract for genomics — and it's the right abstraction", "ADR-001 (platform architecture)",
         "The VCF (Variant Call Format) IS a data contract for genetic variants: CHROM, POS, ID, REF, ALT, QUAL, FILTER, INFO. Each field has a type, a meaning, and a validation rule. This IS the SAME pattern as a database schema (CREATE TABLE) or an Avro schema (JSON + types). The VCF IS the API between the variant caller (BWA+GATK) and the annotator (VEP) and the analyst (PLINK). The contract (typed schema) stays; the implementation (VCF vs BCF vs Parquet) changes. The pattern IS data engineering applied to genomics."),
    ],
}


def replace_generic_thoughts(page_filename, new_thoughts):
    """Replace the generic DeeperThoughtSection content with page-specific thoughts."""
    path = PAGES_DIR / page_filename
    if not path.exists():
        return False, "file not found"
    
    src = path.read_text()
    
    # Check if already upgraded (has page-specific keywords)
    if "IS the" in src and "generic" not in src.lower():
        # Check if the existing thoughts are page-specific
        # by looking for the page-specific keywords in the thought titles
        for title, _, _ in new_thoughts:
            if title.split(" IS ")[0] in src:
                return False, "already has page-specific thoughts"
    
    # Find the DeeperThoughtSection block and replace its children
    # Pattern: <DeeperThoughtSection ...> ... </DeeperThoughtSection>
    # We need to replace the inner content (the <DeeperThought> children)
    
    # Build new JSX
    page_name = page_filename.replace(".tsx", "").replace("-", " ").title()
    jsx = f'<DeeperThoughtSection pageTitle="{page_name}">\n'
    for title, adr, content in new_thoughts:
        title_e = title.replace('"', '\\"')
        adr_e = adr.replace('"', '\\"')
        content_e = content.replace('"', '\\"').replace('\n', ' ')
        jsx += f'        <DeeperThought title="{title_e}" connectedTo="{adr_e}">\n'
        jsx += f'          <p>{{"{content_e}"}}</p>\n'
        jsx += f'        </DeeperThought>\n'
    jsx += f'      </DeeperThoughtSection>'
    
    # Replace the existing DeeperThoughtSection block
    # Find the opening and closing tags
    pattern = r'<DeeperThoughtSection[^>]*>[\s\S]*?</DeeperThoughtSection>'
    match = re.search(pattern, src)
    if match:
        src = src[:match.start()] + jsx + src[match.end():]
        path.write_text(src)
        return True, f"replaced {len(new_thoughts)} thoughts"
    else:
        return False, "DeeperThoughtSection not found"


def main():
    total = 0
    for page_filename, thoughts in UPGRADES.items():
        ok, msg = replace_generic_thoughts(page_filename, thoughts)
        if ok:
            total += 1
            print(f"  + {page_filename}: {msg}")
        else:
            print(f"  = {page_filename}: {msg}")
    print(f"\nUpgraded {total} pages with page-specific thoughts.")


if __name__ == "__main__":
    main()
